version: "3.8"
services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    volumes:
      - "./app/:/usr/src/app"
    command: tail -f /dev/null

